In [1]:
import pandas as pd
import datetime as dt

In [2]:
stk_data=pd.read_csv('Tatacoffee13_21.csv')

In [3]:
stk_data["Date"] = pd.to_datetime(stk_data["Date"])

In [4]:
stk_data = stk_data[
    (stk_data["Date"] >= pd.Timestamp("2020-01-01")) &
    (stk_data["Date"] <= pd.Timestamp("2021-12-31"))
]

In [5]:
stk_data

           Date    Open    High     Low   Close
1728 2020-01-01   92.50   92.70   91.30   91.50
1729 2020-01-02   91.90   93.25   91.55   92.45
1730 2020-01-03   92.70   96.20   92.50   93.90
1731 2020-01-06   92.75   93.25   90.10   90.35
1732 2020-01-07   91.05   92.55   90.50   91.55
...         ...     ...     ...     ...     ...
2220 2021-12-22  202.90  207.80  201.35  205.00
2221 2021-12-23  206.00  206.85  202.05  202.95
2222 2021-12-24  203.90  203.90  199.35  201.00
2223 2021-12-27  200.00  222.00  196.00  218.35
2224 2021-12-28  219.65  220.45  211.55  212.35

[497 rows x 5 columns]

In [6]:
#To pick a particular Column (Use [[]])
stk_data=stk_data[['Open','High','Low','Close']]

In [7]:
stk_data

        Open    High     Low   Close
1728   92.50   92.70   91.30   91.50
1729   91.90   93.25   91.55   92.45
1730   92.70   96.20   92.50   93.90
1731   92.75   93.25   90.10   90.35
1732   91.05   92.55   90.50   91.55
...      ...     ...     ...     ...
2220  202.90  207.80  201.35  205.00
2221  206.00  206.85  202.05  202.95
2222  203.90  203.90  199.35  201.00
2223  200.00  222.00  196.00  218.35
2224  219.65  220.45  211.55  212.35

[497 rows x 4 columns]

In [8]:
column='Close'

In [9]:
"""Time Series is a Univarinate , We are able to create a model for that one particular column (Date--> in the dataset is the TImeSeries data
    close-->Timeseries data,Open,High,Low)"""

'Time Series is a Univarinate , We are able to create a model for that one particular column (Date--> in the dataset is the TImeSeries data\n    close-->Timeseries data,Open,High,Low)'

In [10]:
from sklearn.preprocessing import MinMaxScaler
Ms=MinMaxScaler()
data1=Ms.fit_transform(stk_data[[column]])
print('Len : ',data1.shape)

Len :  (497, 1)

In [11]:
# In TimeSeries Analysis we need a Standardsation or to Normalaisation we gonna use MinMaxScaler

In [12]:
# training and Testset data
training_size=round(len(data1)*0.80) #80 Percentage 
print(training_size)
x_train=data1[:training_size]
x_test=data1[training_size:]
print('X_Train Length : ',x_train.shape)
print('X_Test Length : ',x_test.shape)
y_train=data1[:training_size]
y_test=data1[training_size:]
print('y_train Length : ', y_train.shape)
print('y_test length : ',y_test.shape)

398
X_Train Length :  (398, 1)
X_Test Length :  (99, 1)
y_train Length :  (398, 1)
y_test length :  (99, 1)

In [13]:
''' In time Series Analysis the Test&Training data should be split seriesly

In Machine Learning it will be random but in time series it should be series (Ordered)'''

' In time Series Analysis the Test&Training data should be split seriesly\n\nIn Machine Learning it will be random but in time series it should be series (Ordered)'

In [14]:
#Model Creation 
from sklearn.metrics import mean_squared_error # Metric 
trends=['n','t','c','ct'] # Parameters 
lags=[1,2,3,4]
from statsmodels.tsa.ar_model import AutoReg #Algo Used for Model Cretation
for i in lags:
    for td in trends:
        model=AutoReg(x_train,lags=i,trend=td)
        model_fit=model.fit()
        #Makes Predicts
        y_pred=model_fit.predict(len(x_train),len(data1)-1)
        from Auto_Regression_SF import sf
        print('Lag={},Trend={}'.format(i,td))
        sf.rmsemape(y_test,y_pred)
        print("***********")

Lag=1,Trend=n
RMSE-Testset :  0.31021861167658266
maPe-testset :  0.3144928769698368
***********
Lag=1,Trend=t
RMSE-Testset :  0.11629688207483183
maPe-testset :  0.11926652060265035
***********
Lag=1,Trend=c
RMSE-Testset :  0.3087975417853092
maPe-testset :  0.313130241475749
***********
Lag=1,Trend=ct
RMSE-Testset :  0.15377330485918414
maPe-testset :  0.1583241201885519
***********
Lag=2,Trend=n
RMSE-Testset :  0.30220511948549084
maPe-testset :  0.30733553931107593
***********
Lag=2,Trend=t
RMSE-Testset :  0.10001182624013026
maPe-testset :  0.10189211777619618
***********
Lag=2,Trend=c
RMSE-Testset :  0.28535174771583466
maPe-testset :  0.2910965185152033
***********
Lag=2,Trend=ct
RMSE-Testset :  0.13255861201939304
maPe-testset :  0.1363392546139281
***********
Lag=3,Trend=n
RMSE-Testset :  0.3078797318521575
maPe-testset :  0.31289754299575506
***********
Lag=3,Trend=t
RMSE-Testset :  0.10377804078471377
maPe-testset :  0.10605126176514605
***********
Lag=3,Trend=c
RMSE-Testset :  0.3061201523829243
maPe-testset :  0.3112079599932602
***********
Lag=3,Trend=ct
RMSE-Testset :  0.14261824085371907
maPe-testset :  0.14696794011502445
***********
Lag=4,Trend=n
RMSE-Testset :  0.30996350507453185
maPe-testset :  0.31488585121510226
***********
Lag=4,Trend=t
RMSE-Testset :  0.10347606684884676
maPe-testset :  0.10572444596436088
***********
Lag=4,Trend=c
RMSE-Testset :  0.29209236867819804
maPe-testset :  0.2976952818104322
***********
Lag=4,Trend=ct
RMSE-Testset :  0.1364774180935851
maPe-testset :  0.14053599313567172
***********

C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
C:\Users\USER\anaconda3\envs\aiml\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [15]:
'''Mostly in Time Series , When the value is low (the model work prefertly alright good 
Accuracy)
From This result which score low value through that trends & lags only 
we gonna make a final model'''

'Mostly in Time Series , When the value is low (the model work prefertly alright good \nAccuracy)\nFrom This result which score low value through that trends & lags only \nwe gonna make a final model'

In [16]:
#Forecasting 
forecast=model_fit.predict(len(data1),len(data1)+3)

In [17]:
forecast

array([1.0941548 , 1.09660662, 1.0990623 , 1.1015218 ])

In [18]:
'''  Its in Standardaization change this into Original value '''

'  Its in Standardaization change this into Original value '

In [24]:
#Changing those numbers into Original Values 
from Auto_Regression_SF import sf
fTestNormTable=sf.conversionSingle(forecast,['Closefore'])
forecast_stock_price_test_ori=Ms.inverse_transform(fTestNormTable)
forecast_stock_price_test_oriF=sf.conversionSingle(forecast_stock_price_test_ori,['closefore'])

In [25]:
forecast_stock_price_test_oriF

    closefore
0  253.350456
1  253.807473
2  254.265213
3  254.723664